services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Gedankenfolger\GedankenfolgerPowermailRedirect\:
    resource: '../Classes/'
    exclude:
      - '../Classes/Finisher/'
      - '../Classes/Form/'

  Gedankenfolger\GedankenfolgerPowermailRedirect\EventListener\CreateActionBeforeRenderViewListener:
    tags:
      - name: event.listener
        identifier: 'gedankenfolger-powermail-redirect/createActionBeforeRenderView'
        event: In2code\Powermail\Events\FormControllerCreateActionBeforeRenderViewEvent

  Gedankenfolger\GedankenfolgerPowermailRedirect\EventListener\SuppressPowermailMailsWhenCleverReachActiveListener:
    tags:
      - name: event.listener
        identifier: 'gedankenfolger-powermail-redirect/suppressMailsWhenCleverReachActive'
        event: In2code\Powermail\Events\SendMailServicePrepareAndSendEvent
